# Generated by Django 3.0.6 on 2020-09-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='herramientas',
            options={'verbose_name_plural': 'Herramientas'},
        ),
        migrations.AlterModelOptions(
            name='productos_medicinales',
            options={'verbose_name_plural': 'Productos Medicinales'},
        ),
        migrations.AlterModelOptions(
            name='semillas',
            options={'verbose_name_plural': 'Semillas'},
        ),
        migrations.AlterModelOptions(
            name='suplementos',
            options={'verbose_name_plural': 'Suplementos'},
        ),
    ]
